# Site settings
title: Raphaël Pagé
email: contact@raphaelpage.me
description: Raphaël Pagé’s personal website.
baseurl: ""
url: http://raphaelpage.me
last_modified_at: 2015-07-18

# Author settings
firstname: Raphaël
lastname: Pagé
ordomedic_firstname: Raphael
ordomedic_lastname: Page
github_username: raphaelpage
linkedin_username: raphaelpage
googleplus_username: "+RaphaëlPagé"

# Build settings
markdown: kramdown
permalink: pretty
